alias ll="ls -al"

alias g="git"
alias gl="git log"
alias gb="git branch"
alias gs="git status"
alias ga="git add ."
alias gc="gitmoji -c"
alias gf="git fetch"
alias gco="git checkout"
alias gnb="git checkout -b"
alias gd="git branch -D"
alias gps="git push origin"
alias gpl="git pull origin"
alias gm="git merge"
alias gsl="git stash list"
alias gsp="git stash pop"
alias gss="git stash save"
